name: catkin_lint
on:
  pull_request:
  # push:
  #   branches:
  #     - main
    paths:
      - 'workflowtest/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cache catkin workspace
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/catkin_ws
          key: ${{runner.os}}-catkin-${{hashFiles('**/package.xml')}}
          restore-keys: |
            ${{runner.os}}-catkin-
            ${{runner.os}}-
            
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-catkin-tools
          sudo apt-get install -y python3-pip
          sudo pip3 install catkin-lint

      - name: Setup catkin workspace
        run: | 
          source /opt/ros/noetic/setup.bash
          mkdir -p ${{github.workspace}}/catkin_ws/src
          cd ${{github.workspace}}/catkin_ws/src
          cd ..
          catkin config --init --cmake-args -DSETUPTOOLS_DEB_LAYOUT=OFF
        
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}/catkin_ws/src
      
      - name: Catkin-lint
        run: |
          source /opt/ros/noetic/setup.bash
          cd ${{github.workspace}}/catkin_ws
          rosdep update
          catkin_lint -W2 --explain --ignore unknown_package src/workflowtest
