name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-20.04
    env:
      TEST_CONDITION: ${{ vars.TEST_CONDITION }}  # Acessa a variável do repositório

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Verificar condição
        id: check_condition
        run: |
          echo "Valor de TEST_CONDITION: '$TEST_CONDITION'"
          # Exemplo de condição: verificar se a variável de ambiente "TEST_CONDITION" é "true"
          if [ "$TEST_CONDITION" == "true" ]; then
            echo "Condição atendida: sucesso!"
            exit 0  # Sucesso
          else
            echo "Condição não atendida: falha!"
            exit 1  # Falha
          fi

      - name: Resultado
        if: steps.check_condition.outcome == 'success'
        run: echo "O workflow foi bem-sucedido!"
